### ISSUE TITLE
No loan available

### ISSUE THREAD

**Issue by rossigio** [thicccat688/peerberrypy#10]
Good afternoon, first of all, I wanted to thank you for this magnificent API. I must say that I'm a beginner, I noticed that after a while of using the API from my account, no loans were visible, even though I hadn't set any filters (although in reality, 5-6 long loans were present). How could I solve the problem? I found another way to invest with the API, but I'm not sure if it will last long. Thank you very much for your work.Good afternoon, first of all, I wanted to thank you for this magnificent API. I must say that I'm a beginner, and I noticed that after a while of using the API from my account, no loans were visible, even though I hadn't set any filters (although in reality, 5-6 long loans were present). How could I solve the problem? I found another way to invest with the API, but I'm not sure if it will last long. Thank you very much for your work.

**Comment by thicccat688** [comment]
Hello,

Thank you for your comments, I'm happy to hear the API has been useful for you!

When it comes to your question, the get_loans function doesn't return the loans you're talking about because they probably don't have a group guarantee (If they're the Lithuanian real estate loans). The API excludes loans without a group guarantee by default, so if you want to see them, you have to pass `group_guarantee=False` to the `get_loans` function. 

Let me know if this helped.

**Comment by rossigio** [comment]
Thank you for your prompt response. I am pleased to see your interest in troubleshooting. The issue is that the loans are not visible, even when I log in through the Peerberry smartphone app. The message reads: "there are currently no loans that match your selected criteria." However, these loans are visible on another account. I suspect that Peerberry is able to detect the use of this API, but I am not certain as I am new to programming. Nevertheless, I have been able to work around the issue by using a second account to find loans and then transferring the ID to my primary account during the investment phase. Once again, thank you for your support and effort in developing this API.

**Comment by thicccat688** [comment]
Hello,

No problem and I'm happy to help.

Regarding what you said, Peerberry most likely doesn't detect that you're using their API directly, so it must be some other issue causing your loans to not appear (Even if it did detect this package, it wouldn't hide loans from you in the app).

Have a nice day!
