### ISSUE TITLE
 API.get_loans_page() got multiple values for argument 'self'

### ISSUE THREAD

**Issue by MouTio** [thicccat688/peerberrypy#30]
Hi! 
First of all, thanks for the work :)

I have launched the examples of "Usage" (Readme file):
"print(api_client.get_loans(quantity=100, originators=['Smart Pozyczka PL']))" and it returns this error:

```
>>> print(api_client.get_loans(quantity=100, originators=['Smart Pozyczka PL']))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Nacho\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\peerberrypy\api.py", line 185, in get_loans
    loans_data = do_get_loans_page(page_num)['data']
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: API.get_loans_page() got multiple values for argument 'self'
```

I have tested without "originators" parameter and the result is the same.

The other functions works fine (get_profile and get_investments)

**Comment by RenardFurtif** [comment]
Hi, I have exactly the same error. Unfortunately I don't have the solution, I can't wait to find out.

**Comment by thicccat688** [comment]
@rafalkrupinski Hi, this is related to your changes. Do you know what a fix could be?
