### ISSUE TITLE
failing tests in github actions

### ISSUE THREAD

**Issue by rafalkrupinski** [thicccat688/peerberrypy#33]
Hi,

The tests on github CI are invariably failing. That's not very useful and causes error report fatigue.

I see now they're failing due to missing credentials. Not sure if you want to keep your PB password at GH. If not, a reasonable step would be disabling GH actions.

IMO The only good way to test such a remote API client would be recording real responses and mocking the HTTP requests, so not making any remote API calls. Optionally real tests (against live API) could be run manually.

**Comment by svscorp** [comment]
Maybe I can help with mocking, but not sure if I can do it in the main repository. What's your suggestion: hoverfly/wiremock?

**Comment by thicccat688** [comment]
I will have difficulty with testing because I closed my Peerberry account recently, so for now, I'll remove the GH actions until we have mocks for the HTTP requests so that we don't have to use the Peerberry live API for testing.

**Comment by rafalkrupinski** [comment]
> I closed my Peerberry account recently

And you keep maintaining the project? :)
