### ISSUE TITLE
API.get_loans_page() got multiple values for argument 'self'

### ISSUE THREAD

**Issue by mwolfsp** [thicccat688/peerberrypy#34]
Hey, 

firstly I very much enjoy using this project, it's of great help to me.

Now I'm not a professional dev so it might also be a lack of understanding, but I did quite some digging and experimenting. 

I am getting the following error when trying to get loans:
INFO Exception in getLoans function, error: API.get_loans_page() got multiple values for argument 'self'

Now the strange thing is, I have one poetry virtual environment where the same exact code works, but I am not able to get it running again with a fresh setup. 
I am trying to build a docker container to run as Google Run Job, however it also fails locally. I got some feeling it might have to do with the pandas version on the system, but I was also not able to downgrade that as well trying for hours. In the working environment I have pandas 2.0.3 which seems to work but cannot be installed anymore (tried on Windows locally and in a docker container).

I also got this warning, not sure if that's related: 
FutureWarning: Passing bytes to 'read_excel' is deprecated and will be removed in a future version. To read from a byte string, wrap it in a `BytesIO` object.
  investment_data = pd.read_excel(

**Comment by thicccat688** [comment]
Hello,

I'm glad to hear it's been of use!

I've deployed a new version of the package (1.8.0) that addresses the bug you've brought up with the API.get_loans_page(). If after updating to the newer version it still doesn't work please let me know.

**Comment by thicccat688** [comment]
Alternatively, if it still causes issues, downgrade to the latest stable version of 1.6.0

**Comment by mwolfsp** [comment]
Thanks for the quick fix, it does work with 1.8.0. 

FYI: I noticed that with 1.8.0 I had to install some dependencies manually, like pyotp and openpyxl, which was not the case with 1.7.0
