### ISSUE TITLE
get_loans returns no loans anymore

### ISSUE THREAD

**Issue by mwolfsp** [thicccat688/peerberrypy#38]
Hi,

since a few days the get_loans function does not return anything for me anymore besides the Lithuanian loans that are always available (e.g. real estate).

I have checked this while there were loans available in the morning, e.g. PL or KZ that sit for a minute or two. Still got no returns. I also removed all parameters except for the quantity to check if anything changed there, but still no results.

It's not an account ban, since web and mobile app work fine, also same IP.
They might have changed sth. on their end - could you verifiy this as well and is there any way around?

**Comment by brice-ahouangonou** [comment]
I was facing the same issue until today.
It has started the 5th of December.
A workaround that worked for me is to set the amount of loans to fetch to "1" :
```python
loans = api_client.get_loans(
  # Amount of loans to fetch
  quantity=1
  ....
)
```

**Comment by mwolfsp** [comment]
Exactly, for me as well on 5th.

Thanks for the tip, I will try with quantity=1. 

I guess we can't do much against it.

**Comment by apercu** [comment]
Wow, I just wondered about not investing, but didn't realize it's not working.
I cannot find a difference between the browser and API requests, regarding the parameters. I'm not able to debug more low-level. Did anyone find something?

**Comment by mwolfsp** [comment]
I also did not find anything, but am not really a Dev. 
I ended up rewriting that part of my script with the API call captured from Chrome and it works. Only difference I can really imagine is due to the header data maybe?

**Comment by craftsman95** [comment]
> Exactly, for me as well on 5th.
> 
> Thanks for the tip, I will try with quantity=1.
> 
> I guess we can't do much against it.
> 
> Edit: It now seems to be ignoring the quantity parameter. On the LT loans it just returns all of them and on all other loans nothing... I guess PB is reading this

Yes.
It is now ignoring the quantity parameter.
I am now able to get Long-Term loans without the trick of quantity=1.
But could not get any short-term loan since Dec. 5th 😞
Auto-Invest is also stucked 😞
I guess PB are doing something on their API service.
May be they are limiting the Manual Invest & bot access.

**Comment by brice-ahouangonou** [comment]
> I also did not find anything, but am not really a Dev.
> I ended up rewriting that part of my script with the API call captured from Chrome and it works. Only difference I can really imagine is due to the header data maybe?

Were you able to catch short-term loans that way ?
If yes, it can be good clue to fix the issue.
I will try it.

**Comment by apercu** [comment]
@mwolfsp , can you share some details about using "the API call captured from Chrome" - I don't fully get it.

**Comment by mwolfsp** [comment]
> @mwolfsp , can you share some details about using "the API call captured from Chrome" - I don't fully get it.

You can go to DevTools (F12) - Network, filter by Fetch/XHR and then do whatever you want on the site (e.g. get loans), set filters etc, and it will display you the API calls.

**Comment by apercu** [comment]
Ah OK, I wasn't sure if you did something else, especially around the metadata. 
I compared the request URL (identical) and also compared the request metadata as far as I could get, but still could not find any solution.

**Comment by angelbarrera92** [comment]
Any workaround for this?
It is not working for me to set the quantity to 1. What am I doing wrong?

**Comment by rafalkrupinski** [comment]
Doesn't look like @thicccat688 will work on the project...
I'll look into this.
Have the same issue, but I thought it was about timing...

**Comment by rafalkrupinski** [comment]
I thought `count` was required parameter in `get_loans()`...
Anyway, internally it's calling `get_loans_page()` and that always sends count=40

**Comment by rafalkrupinski** [comment]
Please test against https://github.com/rafalkrupinski/peerberrypy branch `headers`

You should be able to install it with `pip install git+https://github.com/rafalkrupinski/peerberrypy@headers`.

Please continue the discussion in rafalkrupinski/peerberrypy#1

**Comment by rafalkrupinski** [comment]
@mwolfsp 
> I ended up rewriting that part of my script with the API call captured from Chrome and it works. Only difference I can really imagine is due to the header data maybe?

Can you share the code somewhere? which headers headers did you include?
I did add a couple of them in my fork.

**Comment by thicccat688** [comment]
Hey everyone,

Thank you for being patient with this issue. I have not forgotten about this project and I have time this week to look at it.

Thank you especially to @rafalkrupinski for maintaining/forking the project and lending his help.

**Comment by rafalkrupinski** [comment]
@thicccat688 welcome back. I was sure you've abandoned us :)
Edit - I didn't expect you to continue maintaining the library, since you've mentioned you don't invest on PB any more.

There's been changes on the PB side, and they've started to filter bots. That's what I got from Rita. She advised me to contact user support.

**Comment by rafalkrupinski** [comment]
OK, so peerberry actively filters bots, and considers using them an "illicit activity", and so a breach of contract. I don't have time for manual investments, and auto-invest leaves 50% cash drag and growing.

I'm withdrawing all my cash and will no longer participate in this project.

Best of luck.

**Comment by thicccat688** [comment]
@rafalkrupinski Thanks :)

I don't invest on PB anymore, but I'll keep maintaining it since people use this library. 

I've found the issue with the get_loans function. When you don't specify the group_guarantee argument, it only returns the non-group guaranteed loans from the API, meaning the Lithuanian real estate loans are the only ones returned. 

I'll set the group_guarantee argument to default to True, meaning it always returns the guaranteed loans by default, so it'll show all the loans from Poland, Kazakhstan, etc, since they have a group guarantee, unlike the Lithuanian ones. To see the Lithuanian ones all you have to do is pass False for the group_guarantee argument.

I'll deploy the new version soon.

**Comment by rafalkrupinski** [comment]
There might be a bug regarding handling of start_page in get_loans / get_loans_page, if someone wants to take a look

**Comment by svscorp** [comment]
> peerberry actively filters bots, and considers using them an "illicit activity"

Interesting, that platform is trying to filter and fight it, instead of embrace and onboard it. Things are much more efficient in API first world.

@rafalkrupinski where is the information that it's "illicit activity" and break of terms?

**Comment by mwolfsp** [comment]
> OK, so peerberry actively filters bots, and considers using them an "illicit activity", and so a breach of contract. I don't have time for manual investments, and auto-invest leaves 50% cash drag and growing.
> 
> I'm withdrawing all my cash and will no longer participate in this project.
> 
> Best of luck.

Although they stated that on their telegram I don't think they are really doing it, bot protection costs a lot of money and is binding efforts and ressources their IT probably needs to develop the platform. 

Our scripts are really easy to filter if they wanted to (which they are not doing atm).

**Comment by rafalkrupinski** [comment]
> Interesting, that platform is trying to filter and fight it, instead of embrace and onboard it. Things are much more efficient in API first world.

It's efficient for you, but I don't think it's in their interest. Think about the latest changes on the platform. Large manual investors complain. They equalize investments with a larger group of investors. More smaller investors means lower discount tiers.

Also, one of the employees told me they're a platinum investor. Let that sink in. And I don't think they'd be the only one. We're essentially competing against the platform. I've better things to do with my life.

> where is the information that it's "illicit activity" and break of terms?

Conversation with the customer "support". That's their BS interpretation, but that's how it is.

> Although they stated that on their telegram I don't think they are really doing it, bot protection costs a lot of money and is binding efforts and ressources their IT probably needs to develop the platform.
> 
> Our scripts are really easy to filter if they wanted to (which they are not doing atm).

If it's simple, it can't be expensive. They say they do it, and if you guys see that API get_loans returns different loans than the webapp, there's your proof. My bot just suddenly stopped seeing any loans a month ago.

It's been fun project, I've been wanting to make an investment bot for years, and it was fun watching it working while it worked. Pity it will be shelved.

**Comment by thicccat688** [comment]
In the past, they had already placed CloudFlare bot protection, which was easy to contour by using Cloud scraper to bypass their checks; however, if Peerberry gets more aggressive bot detection, then it's not worthwhile to continue working on this project as it will get progressively more challenging to maintain and bypass new checks they may add.

I will look into what protections they're implementing, but if it gets to the stage where they rate limit the loan purchasing or other endpoints, it starts taking too much time to get the data you're looking for via API, making it not worth the hassle. 

If they want to stop investors from using bots, it's exceptionally easy for them; even something as simple as signing their auto-invest API requests is enough to detect which purchases come from their servers and which don't.

Thank you to everyone for using this project, and I hope it was helpful while it worked; however, with the announced changes, I will be discontinuing the project.

**Comment by craftsman95** [comment]
I don't really understand why PB wants to ban bots.
These bots are used by legitimate users of PB and are targetting manual loans.
Also Rita from PB said that only a small amount of the loans are dedicated to manual investments and the biggest part is for Auto Investment.
I understand that the bots can slow the UI experience.
But scaling the PB infrastructure should mitigate the slowness.

**Comment by mwolfsp** [comment]
You guys need to chill - the reason the get_loans stopped working is not bot protection but most likely a minor change on their side or a bug in the code. They have little to no bot protection and I do not encounter any rate limits recently if you use sensible delays.

As mentioned further up my script is still working as before, I only swapped the get_loans method with a self written one where the only notable difference for me was some more headers. You can still get loan pages via the api, no problem.

So it would be very sad if the project here was abandoned due to some rumors about bot protection which are currently not in place at all.

**Comment by rafalkrupinski** [comment]
> even something as simple as signing their auto-invest API requests is enough to detect which purchases come from their servers and which don't.

@thicccat688 auto-invest works completely differently and separate from manual. Bots are supposed to pretend to be human investors with browsers. But of course you're right, they have plenty simple means of detecting and disrupting bots.

>  But scaling the PB infrastructure should mitigate the slowness.

@craftsman95 Why would they invest money and effort just to enable you to better compete with them :D

> I do not encounter any rate limits recently if you use sensible delays.

@mwolfsp that's the definition of rate limiting :D

> some rumors about bot protection which are currently not in place at all.

They might not use fancy and expensive bot protection tools, but they are clearly fighting them, despite saying using them is ok.

thicccat688 was already out since before this. In my case, with the amount I was investing... I can use my time and skills in better ways.

They really don't need to care after anyone in particular, just about the overall user experience. They're overflown with cash.
The employees are investing themselves, so they have motive, means and the opportunity to block bots, or even human users.

You've found a way around it this time, good for you. They might be looking at other irregularities, or not. If it's worth your time and effort, go for it.

**Comment by angelbarrera92** [comment]
> You guys need to chill - the reason the get_loans stopped working is not bot protection but most likely a minor change on their side or a bug in the code. They have little to no bot protection and I do not encounter any rate limits recently if you use sensible delays.
> 
> As mentioned further up my script is still working as before, I only swapped the get_loans method with a self written one where the only notable difference for me was some more headers. You can still get loan pages via the api, no problem.
> 
> So it would be very sad if the project here was abandoned due to some rumors about bot protection which are currently not in place at all.

Be more specific so i can submit a pr :) what headers are missing?
