### ISSUE TITLE
'group_guarantee' and 'exclude_invested_loans' parameters are not correctly checked in get_loans() method

### ISSUE THREAD

**Issue by MrDanao** [thicccat688/peerberrypy#5]
In `API.get_loans()` method, the following parameters are booleans with default value: `group_guarantee`, `exclude_invested_loans`.

However they are not correctly checked:

```python
if group_guarantee is not None:
    loan_params['groupGuarantee'] = 1

if exclude_invested_loans is not None:
    loan_params['hideInvested'] = 1
```

These conditions are never matched.

It should be:

```python
if group_guarantee:
    loan_params['groupGuarantee'] = 1

if exclude_invested_loans:
    loan_params['hideInvested'] = 1
```

**Comment by thicccat688** [comment]
Hello, thanks for spotting this mistake. I've accepted your pull request and closed the issue. Much appreciated!
