### ISSUE TITLE
Exception has occurred: JSONDecodeError

### ISSUE THREAD

**Issue by VictorFatoux** [thicccat688/peerberrypy#7]
Hello, nothing works for me. I always have Exception has occurred: JSONDecodeError

**Comment by thicccat688** [comment]
@VictorFatoux Hi, thanks for reporting this. Can you send me your code so I can take a closer look?

**Comment by thicccat688** [comment]
Update: I've looked in to it and it looks like Peerberry has started using CloudFlare. I will update the package soon to get it to work again.

**Comment by thicccat688** [comment]
Second update: Your code won't be needed anymore as I've made the updates required to bypass Cloudflare. Thank you for reporting this. I'll close this issue later today.

**Comment by VictorFatoux** [comment]
Brilliant ! It works for me thanks a lot. Have a nice day
