### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by RenardFurtif** [thicccat688/peerberrypy#9]
Hi,

I would like to use the "get_profit_overview" function. Unfortunately, I don't know how to write the start and end dates. I wrote "api_client.get_profit_overview(start_date="2022-02-01", end_date="2023-02-01", periodicity="day")". I wanted to know in which format to write the dates.

Can you please help me? Thank you in advance.

**Comment by thicccat688** [comment]
Hi Renard,

In Python, when you handle dates, you usually use a module called datetime to create date objects.

In your case, you'd create a date object this way:

```
from datetime import date 

date(year, month, day)
```

An example specifically for what you need:

```
from peerberrypy import API
from datetime import date


api_client = API(
    email="sample email",
    password="sample password",
    tfa_secret="sample tfa secret",
)


print(api_client.get_profit_overview(start_date=date(2022, 2, 1), end_date=date(2023, 2, 1), periodicity="day"))
```

I hope this helps, and if you have any more questions, please let me know!

**Comment by RenardFurtif** [comment]
Thanks you !
